### ISSUE TITLE
Llama cant find Document

### ISSUE THREAD

**Issue by JackFten** [emirsahin1/llm-axe#13] opened 2024-09-10 13:55 UTC
The python terminal itself can find the document but the llm responds with this:
I'm happy to help! However, I don't see any document provided. Could you please share the document with me? It can be a text, image, or even a brief description of what you'd like me to create a story about. I'll do my best to craft an engaging tale for you!

**Comment by emirsahin1** [comment] 2024-09-11 03:13
Hi, could you please share the code that's giving you this response? Thansk!

**Comment by AT-main** [comment] 2024-10-03 18:29
I have the same issue when trying to run the example file `examples/ex_pdf_reader.py`

**Comment by emirsahin1** [comment] 2024-10-03 22:42
Hi, I was able to reproduce the issue by using a very large pdf. The current setup seemed to not work well with larger pdfs. I've modified the PdfReader and it seems to be working as intended now. It should be fixed in 1.1.8 which is released.

Let me know if you are still having issues. Thanks!

**Closed by emirsahin1** 2024-10-03 22:42 UTC
